options:
  iface:
    type: string
    default: eth0
    description: |
      Interface to bind flannel overlay networking to. Defaults to eth0.
  cidr:
    type: string
    default: 10.1.0.0/16
    description: |
      Network CIDR to assign to Flannel
