options:
  iface:
    type: string
    default: ""
    description: |
      The interface to bind flannel overlay networking. The default value is
      the result of running the following command: 
      `route | grep default | head -n 1 | awk {'print $8'}`.
  cidr:
    type: string
    default: 10.1.0.0/16
    description: |
      Network CIDR to assign to Flannel
  etcd_image:
    type: string
    default: gcr.io/google_containers/etcd:2.0.12
    description: |
      The image to pull for the 'etcdctl' command. Recommended to
      mirror the default on a private registry if connectivity is a concern
  flannel_image:
    type: string
    default: quay.io/coreos/flannel:0.5.5
    description: |
      The image to pull for running 'flannel'. Recommended to
      mirror the default on a private registry if connectivity is a concern
