options:
  iface:
    type: string
    default: ""
    description: |
      The interface to bind flannel overlay networking. The default value is
      the result of running the following command:
      `route | grep default | head -n 1 | awk {'print $8'}`.
  cidr:
    type: string
    default: 10.1.0.0/16
    description: |
      Network CIDR to assign to Flannel
