options:
  iface:
    type: string
    default: ""
    description: |
      The interface to bind flannel overlay networking. The default value is
      the interface bound to the cni endpoint.
  cidr:
    type: string
    default: 10.1.0.0/16
    description: |
      Network CIDR to assign to Flannel
