flannel:
  restart: always
  image: {{ flannel_image }}
  volumes:
    - /dev/net:/dev/net
    - {{ charm_dir }}:/run/flannel
  net: host
  privileged: true
  command:
    - /opt/bin/flanneld
    - -iface={{ iface }}
    - -etcd-endpoints={{ connection_string }}
