flannel:
  restart: always
  image: {{ flannel_image }}
  volumes:
    - /dev/net:/dev/net
    - {{ charm_dir }}:/run/flannel
    {% if cert_path -%}
    - {{ cert_path }}:/tls
    {%- endif %}
  net: host
  privileged: true
  command:
    - /opt/bin/flanneld
    - -iface={{ iface }}
    - -etcd-endpoints={{ connection_string }}
    {% if cert_path -%}
    - --remote-certfile=/tls/client-cert.pem
    - --remote-keyfile=/tls/client-key.pem
    - --remote-cafile=/tls/client-ca.pem
    {%- endif %}
